spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/scope
    username: postgres
    password: 14414123
    driver-class-name: org.postgresql.Driver
  freemarker:
    suffix: .ftl
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  sql:
    init:
      platform: postgres
  mail:
    host: smtp.gmail.com
    port: 25
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
bot:
  name:
  token:
